version: '3'
services:
   db:
     container_name: db_jenkins_bot
     build:
       context: . 
       dockerfile: Dockerfile_db
     environment:
       - MYSQL_ROOT_PASSWORD=mysql_root_pass
     restart: always

   jenkins_bot_rtm:
     build:
       context: . 
       dockerfile: Dockerfile_bot
     image: base-image:1
     container_name: jenkins_slack_bot_rtm
     depends_on: 
       - db
     entrypoint: python3 slackbot.py
     env_file:
        - ./vars.env
     restart: always

   jenkins_bot_event:
     image: base-image:1
     container_name: jenkins_slack_bot_event
     depends_on: 
       - jenkins_bot_rtm
     ports:
      - "8080:80" # set publicly exposed port (8080) to receive the events from slack to your HOST MACHINE.
     entrypoint: python3 start_app.py
     env_file:
        - ./vars.env
     restart: always

