FROM mysql:5.7

# File Author / Maintainer
MAINTAINER Vivek/Denny/scavara

COPY init.sql /docker-entrypoint-initdb.d/

RUN chmod 755 /docker-entrypoint-initdb.d/init.sql

RUN rm -rf /var/lib/apt/lists/* && \
rm -rf /var/cache/apk/*

