# Set the base image (latest atm - 12/2020)
FROM python:3.9.1-buster

# File Author / Maintainer
MAINTAINER Vivek/Denny/scavara

RUN apt-get -yqq update

WORKDIR /root/bot

COPY python_mysql.py slack_cmd_process.py slack_message.py slackbot.py start_app.py /root/bot/

COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN rm -rf /var/lib/apt/lists/* && \
rm -rf /var/cache/apk/*

ENV PYTHONUNBUFFERED=0
